<a href="https://colab.research.google.com/github/ccastaneda-boot/datawarehouse-seguros/blob/main/Aseguradoras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://raw.githubusercontent.com/ccastaneda-boot/datawarehouse-seguros/refs/heads/main/data/clientes.csv

In [18]:
url="https://raw.githubusercontent.com/ccastaneda-boot/datawarehouse-seguros/refs/heads/main/data/aseguradoras.csv"

In [19]:
#Adicionamos librería Panda
import pandas as pd

In [20]:
#Lectura del archivo
df = pd.read_csv(url)
print("Dataset Cargado Correctamente")

Dataset Cargado Correctamente

In [21]:
#Verificando cabecera del archivo.
display(df.head())

   id_aseguradora         nombre         pais rating_riesgo
0               1  Aseguradora 1   Costa Rica          Alto
1               2  Aseguradora 2  El Salvador          Bajo
2               3  Aseguradora 3  El Salvador           NaN
3               4  Aseguradora 4   Costa Rica         Medio
4               5  Aseguradora 5   ElSalvador             B


**BLOQUE 2: Exploracion del DATASET (Calidad del dato)**

In [22]:
print("Primeras filas del dataset")
display(df.head())

Primeras filas del dataset

   id_aseguradora         nombre         pais rating_riesgo
0               1  Aseguradora 1   Costa Rica          Alto
1               2  Aseguradora 2  El Salvador          Bajo
2               3  Aseguradora 3  El Salvador           NaN
3               4  Aseguradora 4   Costa Rica         Medio
4               5  Aseguradora 5   ElSalvador             B

In [23]:
print("Dimensiones del dataset (filas, columnas)")
print(df.shape)

Dimensiones del dataset (filas, columnas)
(15, 4)

In [24]:
print("Columnas del dataset")
print(df.columns)

Columnas del dataset
Index(['id_aseguradora', 'nombre', 'pais', 'rating_riesgo'], dtype='object')

In [25]:
print("Tipo de datos")
print(df.dtypes)

Tipo de datos
id_aseguradora     int64
nombre            object
pais              object
rating_riesgo     object
dtype: object

In [26]:
print("Valores nulos")
print(df.isnull().sum())

Valores nulos
id_aseguradora    0
nombre            0
pais              2
rating_riesgo     3
dtype: int64

In [27]:
print ("valores duplicados")
print(df.duplicated().sum())

valores duplicados
0

**BLOQUE 3: LIMPIEZA DE DATOS**

In [30]:
#Elimina espacios al inicio y al final en columnas de texto
for col in df.select_dtypes(include="object").columns:df[col]=df[col].str.strip()

In [1]:
#Normalizar el nombre
df["nombre"]=df["nombre"].str.title()

NameError: name 'df' is not defined